/*
 * Simple GAIN API
 * This is a simple API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: bill.hennessy@maritz.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.64
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The EligibilityItem model module.
 * @module model/EligibilityItem
 * @version 1.0.0
 */
export default class EligibilityItem {
  /**
   * Constructs a new <code>EligibilityItem</code>.
   * @alias module:model/EligibilityItem
   * @class
   * @param mkid {String} 
   * @param product {String} 
   * @param eligible {String} 
   */
  constructor(mkid, product, eligible) {
    this.mkid = mkid;
    this.product = product;
    this.eligible = eligible;
  }

  /**
   * Constructs a <code>EligibilityItem</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/EligibilityItem} obj Optional instance to populate.
   * @return {module:model/EligibilityItem} The populated <code>EligibilityItem</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new EligibilityItem();
      if (data.hasOwnProperty('mkid'))
        obj.mkid = ApiClient.convertToType(data['mkid'], 'String');
      if (data.hasOwnProperty('product'))
        obj.product = ApiClient.convertToType(data['product'], 'String');
      if (data.hasOwnProperty('eligible'))
        obj.eligible = ApiClient.convertToType(data['eligible'], 'String');
      if (data.hasOwnProperty('releaseDate'))
        obj.releaseDate = ApiClient.convertToType(data['releaseDate'], 'Date');
    }
    return obj;
  }
}

/**
 * @member {String} mkid
 */
EligibilityItem.prototype.mkid = undefined;

/**
 * @member {String} product
 */
EligibilityItem.prototype.product = undefined;

/**
 * @member {String} eligible
 */
EligibilityItem.prototype.eligible = undefined;

/**
 * @member {Date} releaseDate
 */
EligibilityItem.prototype.releaseDate = undefined;

