/*
 * Simple GAIN API
 * This is a simple API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: bill.hennessy@maritz.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.64
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from "../ApiClient";
import EligibilityItem from '../model/EligibilityItem';

/**
* Developers service.
* @module api/DevelopersApi
* @version 1.0.0
*/
export default class DevelopersApi {

    /**
    * Constructs a new DevelopersApi. 
    * @alias module:api/DevelopersApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instanc
    e} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Callback function to receive the result of the addEligibility operation.
     * @callback moduleapi/DevelopersApi~addEligibilityCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * adds a product eligibility record
     * Adds an eligible product to an injector&#x27;s record (required)
     * @param {Object} opts Optional parameters
     * @param {module:model/EligibilityItem} opts.body Eligibility item to add
     * @param {module:api/DevelopersApi~addEligibilityCallback} callback The callback function, accepting three arguments: error, data, response
     */
    addEligibility(opts, callback) {
      opts = opts || {};
      let postBody = opts['body'];

      let pathParams = {
        
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = [];
      let returnType = null;

      return this.apiClient.callApi(
        '/gain', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the searchInjectors operation.
     * @callback moduleapi/DevelopersApi~searchInjectorsCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/EligibilityItem>{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * searches injectors
     * By passing in the appropriate MKID, you can search for available injectors in the system (nice to have, not required) 
     * @param {Object} opts Optional parameters
     * @param {String} opts.searchString pass an optional search string for looking up injectors
     * @param {Number} opts.limit maximum number of records to return
     * @param {module:api/DevelopersApi~searchInjectorsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    searchInjectors(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
        
      };
      let queryParams = {
        'searchString': opts['searchString'],'limit': opts['limit']
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [EligibilityItem];

      return this.apiClient.callApi(
        '/gain', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

}