/*
 * Simple GAIN API
 * This is a simple API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: bill.hennessy@maritz.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.64
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SimpleGainApi);
  }
}(this, function(expect, SimpleGainApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SimpleGainApi.DevelopersApi();
  });

  describe('(package)', function() {
    describe('DevelopersApi', function() {
      describe('addEligibility', function() {
        it('should call addEligibility successfully', function(done) {
          // TODO: uncomment, update parameter values for addEligibility call
          /*
          var opts = {};

          instance.addEligibility(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('searchInjectors', function() {
        it('should call searchInjectors successfully', function(done) {
          // TODO: uncomment, update parameter values for searchInjectors call and complete the assertions
          /*
          var opts = {};

          instance.searchInjectors(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            let dataCtr = data;
            expect(dataCtr).to.be.an(Array);
            expect(dataCtr).to.not.be.empty();
            for (let p in dataCtr) {
              let data = dataCtr[p];
              expect(data).to.be.a(SimpleGainApi.EligibilityItem);
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
